"""first_revision

Revision ID: 12dbff8745ee
Revises: 
Create Date: 2022-05-29 09:13:16.550989

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12dbff8745ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('age', sa.Integer(), nullable=False))
    op.alter_column('product', 'id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    autoincrement=True)
    op.drop_column('product', 'age')
    # ### end Alembic commands ###
